server:
  port: 8012

spring:
  application:
    name: sap-events
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:feign-db;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: true
    generate-ddl: true
    hiberante:
      ddl-auto: update
      sql: debug
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

feign:
  client:
    config:
      cityWebserviceGetCityClient:
        loggerLevel: FULL
        requestInterceptors:
#          - app.feign.city.adapter.out.web.interceptor.GetCityClientInterceptor

city-webservice:
  url: http://localhost:8080/
  username: challenge
  password: challenge
